# Generated by Django 5.1.1 on 2026-09-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code_example',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='code_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='learning_goal',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='post',
            name='practice_task',
            field=models.TextField(blank=True),
        ),
    ]
